### ISSUE TITLE
remove password complexity requirements

### ISSUE THREAD

**Issue by menklab** [menkveldj/sparitcus-file-services#11]
add complexity rating for visual feedback

**Comment by tuxxy** [comment]
Might I recommend the use of [zxcvbn](https://github.com/dropbox/zxcvbn)? It supports the standard that entropy is a means to security instead of length or complexity.

Maybe get rid of complexity requirements and only use an entropy requirement?

**Comment by menklab** [comment]
great idea!

**Comment by menklab** [comment]
done.
